name: ru_app
description: "O RU Digital UFPA é um aplicativo desenvolvido para facilitar a rotina alimentar dos consumidores do Restaurante Universitário (RU) da Universidade Federal do Pará (UFPA), fornecendo informações atualizadas sobre o cardápio diário e os serviços do RU."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.0+47

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_messaging: ^15.0.4
  firebase_core: ^3.3.0
  animated_text_kit: ^4.2.2
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.3.0
  carousel_slider: ^5.0.0
  intl: ^0.20.1
  http: ^1.2.2
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
